name: Semantic Release

on:
  workflow_call:
    secrets:
      token:
        required: false
        description:
          "A secret containing a Github PAT"
    outputs:
      new_release_published:
        description: "Whether a new release was published (true or false)"
        value: ${{ jobs.release.outputs.new_release_published }}
      new_release_version:
        description: "Version of the new release e.g. `1.3.0`"
        value: ${{ jobs.release.outputs.new_release_version }}
      new_release_major_version:
        description: "Major version of the new release e.g. `1`"
        value: ${{ jobs.release.outputs.new_release_major_version }}
      new_release_minor_version:
        description: "Minor version of the new release e.g. `3`"
        value: ${{ jobs.release.outputs.new_release_minor_version }}
      new_release_patch_version:
        description: "Patch version of the new release e.g. `0`"
        value: ${{ jobs.release.outputs.new_release_patch_version }}
      new_release_notes:
        description: "The release notes for the new release"
        value: ${{ jobs.release.outputs.new_release_notes }}
      last_release_version:
        description: "Version of the last release e.g. `1.2.0`, if there was one"
        value: ${{ jobs.release.outputs.last_release_version }}
      ref-slug:
        description: "A URL sanitized version of the github ref"
        value: ${{ jobs.release.outputs.ref-slug }}
      short-sha:
        description: "Captures the short SHA for use in this or later workflow jobs"
        value: ${{ jobs.release.outputs.short-sha }}

permissions:
  actions: read
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-24.04
    outputs:
      new_release_published: ${{ steps.semantic-release.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic-release.outputs.new_release_version }}
      new_release_notes: ${{ steps.semantic-release.outputs.new_release_notes }}
      new_release_major_version: ${{ steps.semantic-release.outputs.new_release_major_version }}
      new_release_minor_version: ${{ steps.semantic-release.outputs.new_release_minor_version }}
      new_release_patch_version: ${{ steps.semantic-release.outputs.new_release_patch_version }}
      last_release_version: ${{ steps.semantic-release.outputs.last_release_version }}
      short-sha: ${{ env.GITHUB_SHA_SHORT }}
      ref-slug: ${{ env.GITHUB_REF_SLUG_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Slugify github variables
        uses: rlespinasse/github-slug-action@v5.0.0
      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_USER_PAT }}
        with:
          semantic_version: v24.2.1
          extra_plugins: |
            @semantic-release/git@10.0.1
            @semantic-release/changelog@6.0.3
            @semantic-release/exec@7.0.2
            conventional-changelog-conventionalcommits@8.0.0
      - name: Success summary
        if: ${{ steps.semantic-release.outputs.new_release_published == 'true' }}
        run: |
          echo "
          ### :bookmark: ✅ New release created (${{ steps.semantic-release.outputs.new_release_version }})

          **Release Notes:**

          ${{ steps.semantic-release.outputs.new_release_notes }}
          " >> $GITHUB_STEP_SUMMARY